import { Geist, Geist_Mono , Poppins, Orbitron, Share_Tech_Mono } from "next/font/google";
import "./globals.css";
import SmoothScrollWrapper from "./components/SmoothScrollerWrapper";
import AuthProvider from "./authProvider";
import TechCursor from "./components/techCursor";

const geistSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

const shareTechMono = Share_Tech_Mono({
  variable: "--font-share-tech-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${shareTechMono.variable} antialiased "light"`}>
      <body
        className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} ${orbitron.variable} ${shareTechMono.variable} antialiased`}
      >
        <AuthProvider>
          <TechCursor />
          <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
